### ISSUE TITLE
AliView not running in Ubuntu 18.04

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/PoonLab#81]
```
INFO  2018-08-30 14:08:29,943 AliView               415 - error was caught
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```

**Comment by ArtPoon** [comment]
Known issue:
https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1788250

**Comment by ArtPoon** [comment]
Workaround indicated in bug report (comment out line in `/etc/java-*-openjdk/accessibility.properties`) works for AliView and BEAST but not FigTree.
